trigger:
- main

variables:
  # ACR name and image info
  azureContainerRepository: acronlinestoredevuksouth001.azurecr.io
  imageName: order
  imageTag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and publish stage
    jobs:
      - job: Build
        displayName: Build Job
        steps:
          - script: |
              echo "Listing source directory:"
              ls -R "$(System.DefaultWorkingDirectory)"
              echo "Listing build directory:"
              ls -R "$(Agent.BuildDirectory)"
            displayName: 'List Directories'

          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'

          
          - task: Docker@2
            displayName: Build and publish image to Azure Container Registry
            inputs:
              command: buildAndPush
              containerRegistry: 'acr-svc-connection'
              repository: $(azureContainerRepository)
              Dockerfile: '$(Build.sourcesdirectory)/app/order-service/Dockerfile'
              tags: $(tags)

# steps:
# - script: |
#     echo "Listing source directory:"
#     ls -R "$(System.DefaultWorkingDirectory)"
#     echo "Listing build directory:"
#     ls -R "$(Agent.BuildDirectory)"
#   displayName: 'List Directories'

# - task: AzureCLI@2
#   displayName: 'Build and Push Docker Image'
#   inputs:
#     azureSubscription: 'My Azure Connection Name'  # service connection name
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       echo "Logging into ACR..."
#       az acr login --name $(acrName)

#       echo "Building Docker image..."
#       docker build -t $(acrName)/$(imageName):$(imageTag) .   

#       echo "Tagging 'latest' version..."
#       docker tag $(acrName)/$(imageName):$(imageTag) $(acrName)/$(imageName):latest
#       docker push $(acrName)/$(imageName):latest
  



# echo "Pushing Docker image to ACR..."
# docker push $(acrName)/$(imageName):$(imageTag)