trigger:
- main

variables:
  # Image info
  imageName: order
  tag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and publish stage
    jobs:
      - job: Build
        displayName: Build Job
        steps:
          - script: |
              echo "Listing source directory:"
              ls -R "$(System.DefaultWorkingDirectory)"
              echo "Listing build directory:"
              ls -R "$(Agent.BuildDirectory)"
            displayName: 'List Directories'

          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          
          - task: Docker@2
            displayName: Build and publish image to ACR
            inputs:
              command: buildAndPush
              containerRegistry: 'acr-svc-connection'
              repository: $(imageName)
              Dockerfile: '$(Build.sourcesdirectory)/app/order-service/Dockerfile'
              tags: |
                $(tag)