pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: 'arm-svc-con'
  aksCluster: 'aks-onlinestore-dev-uksouth-001'
  aksResourceGroup: 'rg-onlinestore-dev-uksouth-001'
  namespace: 'default' # or custom namespace
  manifestsPath: 'manifests/' # folder where your YAML files are

stages:
  # - stage: PublishArtifact
  #   displayName: "Publish Pipeline Artifact"
  #   jobs:
  #     - job: PublishManifest
  #       displayName: "Publish Manifest"
  #       steps:
  #         - task: PublishPipelineArtifact@1
  #           inputs:
  #             artifactName: 'manifests'
  #             path: 'manifests'

  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
    - job: Deploy
      displayName: Deploy
      pool:
        vmImage: ubuntu-latest
      steps:
      # - task: AzureCLI@2
      #   displayName: 'Azure CLI: Connect to AKS'
      #   inputs:
      #     azureSubscription: $(serviceConnection)
      #     scriptType: 'bash'
      #     scriptLocation: 'inlineScript'
      #     inlineScript: |
      #       az account set --subscription 'b798c28b-e334-4ecf-b338-ec314ced3616'
      #       az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksCluster) --overwrite-existing

      - task: KubernetesManifest@1
        displayName: Deploy Order Service
        inputs:
          action: 'deploy'
          connectionType: 'azureResourceManager'
          azureSubscriptionConnection: $(serviceConnection)
          azureResourceGroup: $(aksResourceGroup)
          kubernetesCluster: $(aksCluster)
          manifests: $(Build.sourcesdirectory)/manifests/