# name: 1.0.$(BuildID)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: "Infra Validatation"
    jobs:
      - template: infraTemplates/infravalidation.yml
        parameters:
          environment: "dev"
          serviceconnection: "arm-svc-con"

  - stage: Dev
    displayName: "Dev"
    jobs:
      - template: infraTemplates/deployresources.yml
        parameters:
          environment: "dev"
          serviceconnection: "arm-svc-con"