trigger:
- main

variables:
  # Image info
  imageName: store-front
  tag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and publish stage
    jobs:
      - job: BuildPublishDockerImages
        displayName: Build Publish Docker Images
        steps:
          - script: |
              echo "Listing source directory:"
              ls -R "$(System.DefaultWorkingDirectory)"
              echo "Listing build directory:"
              ls -R "$(Agent.BuildDirectory)"
            displayName: 'List Directories'

          - task: DockerInstaller@0
            displayName: Install Docker
            inputs:
              dockerVersion: '17.09.0-ce'

          - template: appTemplates/build.yml
            parameters:
              acrServiceConnection: 'acr-svc-connection'
              imageName: $(imageName)
              dockerFilePath: '$(Build.sourcesdirectory)/app/store-front/Dockerfile'
              tag: $(tag)