trigger: none

variables:
  serviceConnection: 'arm-svc-con'
  aksCluster: 'aks-onlinestore-dev-uksouth-001'
  aksResourceGroup: 'rg-onlinestore-dev-uksouth-001'
  namespace: 'default' # or custom namespace
  manifestsPath: 'manifests/' # folder where your YAML files are
  # Image info
  imageName: store-front
  #tag: $(Build.BuildId)
  tag: latest

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and publish stage
    jobs:
      - job: BuildPublishDockerImages
        displayName: Build Publish Docker Images
        steps:
          - task: DockerInstaller@0
            displayName: Install Docker
            inputs:
              dockerVersion: '17.09.0-ce'

          - template: appTemplates/build.yml
            parameters:
              acrServiceConnection: 'acr-svc-connection'
              imageName: $(imageName)
              dockerFilePath: '$(Build.sourcesdirectory)/app/store-front/Dockerfile'
              tag: $(tag)
  
  # - stage: Deploy
  #   displayName: Deploy store-front Service in AKS
  #   jobs:     
  #     - job: DeplyUsingManifest
  #       steps:       
  #         - task: KubernetesManifest@1
  #           displayName: Deploy store-front Service
  #           inputs:
  #             action: 'deploy'
  #             connectionType: 'azureResourceManager'
  #             azureSubscriptionConnection: $(serviceConnection)
  #             azureResourceGroup: $(aksResourceGroup)
  #             kubernetesCluster: $(aksCluster)
  #             manifests: |
  #               $(Build.sourcesdirectory)/manifests/store-front-deployment.yml
  #               $(Build.sourcesdirectory)/manifests/store-front-service.yml