parameters:
- name: "acrServiceConnection"
  type: string
- name: "imageName"
  type: string
- name: "dockerFilePath"
  type: string
- name: "tag"
  type: string

jobs:
  - job: Build
    displayName: Build Job
    steps:      
      - task: Docker@2
        displayName: Build and publish image to ACR
        inputs:
          command: buildAndPush
          containerRegistry: $(acrServiceConnection)
          repository: $(imageName)
          Dockerfile: $(dockerFilePath)
          tags: |
            $(tag)