parameters:
- name: "acrServiceConnection"
  type: string
- name: "imageName"
  type: string
- name: "dockerFilePath"
  type: string
- name: "tag"
  type: string

jobs:
  - job: Build
    displayName: Build ${{parameters.imageName}}
    steps:      
      - task: Docker@2
        displayName: Build and publish ${{parameters.imageName}} to ACR
        inputs:
          command: buildAndPush
          containerRegistry: ${{parameters.acrServiceConnection}}
          repository: ${{parameters.imageName}}
          Dockerfile: ${{parameters.dockerFilePath}}
          tags: |
            ${{parameters.tag}}

